apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment-blue
spec:
  replicas: 7
  selector:
    matchLabels:
      app: spring
      version: blue
  template:
    metadata:
      labels:
        app: spring
        version: blue
    spec:
      containers:
      - name: petclinic
        image: 636706114596.dkr.ecr.ap-south-1.amazonaws.com/petclinic-monitoring:latest
        ports:
        - containerPort: 8080
