apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment-green
spec:
  replicas: 7
  selector:
    matchLabels:
      app: spring
      version: green
  template:
    metadata:
      labels:
        app: spring
        version: green
    spec:
      containers:
      - name: petclinic
        image: 636706114596.dkr.ecr.ap-south-1.amazonaws.com/ecomm-repo:latest
        ports:
        - containerPort: 8080
